### PR TITLE
Rescan button over the wordlists manager

### PR DESCRIPTION
**Pull request by ForlaxPy**
#291

### CODE REVIEW

**Comment by openbullet** [comment]
The name is misleading, one might think it works the same way as the Configs if you call it Rescan. Please call it something like Delete Not Found (both the text on the button and the variable names).

**Comment by noammiz007** [comment]
@openbullet 
Now it's fine i guess, Would you mind adding it? ^_^

**Comment by openbullet** [comment]
Yes of course, I wasn't home

**Comment by openbullet** [comment]
Next time please don't add those merges to the PR since it's not editing the same piece of code you don't need to do that ok?

**Pull request merged**
