### PR TITLE
In case if the allowed wordlists were empty.

### PR DESCRIPTION
**Pull request by ForlaxPy**

### CODE REVIEW

**Comment by openbullet** [comment]
I honestly don't think we should forbid the user to run a Config if the maker forgot to set allowed wordlist types, and since those are customizable they might not match in the two Environment files (the one of the maker and the one of the user) so that would get people pretty frustrated. What do you think?

**Comment by meinname** [comment]
yep - i think it is addressing the wrong person.
As it is addressing the user and not the config maker.

But adding a popup at saving a config it maybe nag configmakers who save often and disturbs their "flow".
So yep, maybe there should be some kind of warning for the configmaker - but i don't know where and when and what ;)

**Comment by ForlaxPy** [comment]
well a lot of OB users claim that it's broken and not working, also for Config makers they ain't used to the current system as BB used to set these data auto to MailPass so maybe a little warning like what @meinname stated would do the job if you don't agree on forbidding em from running the Config. 
Also that there should be at least a type of allowed wordlists but yeah that's up to you.

**Comment by openbullet** [comment]
I will close this and warn the config maker in some other way!

**Pull request closed without merging**
