### PR TITLE
Added a locker for BotData#Random & improved/optimized RandomString function using RegEx

### PR DESCRIPTION
**Pull request by Laiteux**

### CODE REVIEW

**Comment by openbullet** [comment]
Thanks, I will review this as soon as possible. Next time please merge it into the develop branch as I'm doing some heavy changes in there and so we will avoid merge conflicts when i merge develop into master. Thanks!

**Comment by Laiteux** [comment]
Sure thing! Want me to also make a PR for the develop branch or will you do that yourself?

**Comment by Laiteux** [comment]
Quick question as I don't know where else to ask it... _([Telegram ](https://t.me/Laiteux) if ever)_

There: https://github.com/openbullet/openbullet/blob/master/RuriLib/Functions/Requests/Request.cs#L73-L82

Why don't you simply use [Uri.EscapeUriString(String)](https://docs.microsoft.com/fr-fr/dotnet/api/system.uri.escapeuristring?view=netframework-4.8)?

**Comment by openbullet** [comment]
@Laiteux if you could make one for the develop branch and close this it would be great thanks, otherwise all fine, I don't think this will cause any conflicts.

**Comment by Laiteux** [comment]
Will do very soon.

**Comment by openbullet** [comment]
Regarding any question you might have, you can hit me up in the forum's DMs at https://forum.openbullet.dev 
I also saw a post about the weird escape string code, it's because the builtin function can only handle strings that are smaller than a certain quantity so I have to split it in chunks or it throws an error on very long strings.

**Pull request closed without merging**
