### PR TITLE
Working build on DotNet 4.7.2 with correct netstandard references

### PR DESCRIPTION
**Pull request by kernelzeroday**
targeting latest stable Extreme.Net 

Booyakasha

### CODE REVIEW

**Comment by kernelzeroday** [comment]
I managed to fix it on my tree, targeting the latest version of dotnet, and the latest stable Extreme.Net built with the Extreme.Net-1.1.0.0 tarball. 

All I had to do was click some autofix button in visual studio, who would have thunk it.

**Comment by kernelzeroday** [comment]
```
1>------ Build started: Project: RuriLib, Configuration: Debug Any CPU ------
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(1964,5): warning MSB3277: Found conflicts between different versions of the same dependent assembly that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed.
1>  RuriLib -> C:\Users\kelsey\openbullet\RuriLib\bin\Debug\RuriLib.dll
2>------ Build started: Project: OpenBullet, Configuration: Debug Any CPU ------
3>------ Build started: Project: OpenBulletCLI, Configuration: Debug Any CPU ------
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(1964,5): warning MSB3277: Found conflicts between different versions of the same dependent assembly that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed.
2>  OpenBullet -> C:\Users\kelsey\openbullet\OpenBullet\bin\Debug\OpenBullet.exe
2>          1 file(s) copied.
2>          1 file(s) copied.
3>  OpenBulletCLI -> C:\Users\kelsey\openbullet\OpenBulletCLI\bin\Debug\OpenBulletCLI.exe
========== Build: 3 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
```

Build log for proof

**Comment by kernelzeroday** [comment]
I guess I need to work on whatever the hell these conflicts are now :)

**Comment by openbullet** [comment]
I think it builds fine as it is now mate, I feel like merging this would cause more problems

**Comment by kernelzeroday** [comment]
What about the missing netstandard reference? On a completely vanilla VS 2017 enterprise with every component available it failed to build with the given instructions, and visual studio itself fixed the missing reference automatically. What issues does this pull request introduce, I'm happy to resolve them if you think targeting the latest for net and nuget packages with associated speed improvements and bug fixes is bad I'm happy to retarget 4.5?

**Comment by kernelzeroday** [comment]
Here's your repo's build log for reference again follow your build instructions to the letter..............

```
Restoring NuGet packages...
To prevent NuGet from restoring packages during build, open the Visual Studio Options dialog, click on the Package Manager node and uncheck 'Allow NuGet to download missing packages during build.'
1>------ Build started: Project: RuriLib, Configuration: Debug Any CPU ------
1>  RuriLib -> C:\Users\kelsey\fucked\openbullet\RuriLib\bin\Debug\RuriLib.dll
2>------ Build started: Project: OpenBullet, Configuration: Debug Any CPU ------
3>------ Build started: Project: OpenBulletCLI, Configuration: Debug Any CPU ------
3>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(1964,5): warning MSB3277: Found conflicts between different versions of the same dependent assembly that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed.
3>C:\Users\kelsey\fucked\openbullet\OpenBulletCLI\Program.cs(41,14,41,20): error CS0012: The type 'Attribute' is defined in an assembly that is not referenced. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
3>C:\Users\kelsey\fucked\openbullet\OpenBulletCLI\Program.cs(44,14,44,20): error CS0012: The type 'Attribute' is defined in an assembly that is not referenced. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
3>C:\Users\kelsey\fucked\openbullet\OpenBulletCLI\Program.cs(47,14,47,20): error CS0012: The type 'Attribute' is defined in an assembly that is not referenced. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
3>C:\Users\kelsey\fucked\openbullet\OpenBulletCLI\Program.cs(50,14,50,20): error CS0012: The type 'Attribute' is defined in an assembly that is not referenced. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
3>C:\Users\kelsey\fucked\openbullet\OpenBulletCLI\Program.cs(53,14,53,20): error CS0012: The type 'Attribute' is defined in an assembly that is not referenced. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
3>C:\Users\kelsey\fucked\openbullet\OpenBulletCLI\Program.cs(56,14,56,20): error CS0012: The type 'Attribute' is defined in an assembly that is not referenced. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
3>C:\Users\kelsey\fucked\openbullet\OpenBulletCLI\Program.cs(59,14,59,20): error CS0012: The type 'Attribute' is defined in an assembly that is not referenced. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
3>C:\Users\kelsey\fucked\openbullet\OpenBulletCLI\Program.cs(62,14,62,20): error CS0012: The type 'Attribute' is defined in an assembly that is not referenced. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
3>C:\Users\kelsey\fucked\openbullet\OpenBulletCLI\Program.cs(65,14,65,20): error CS0012: The type 'Attribute' is defined in an assembly that is not referenced. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
3>C:\Users\kelsey\fucked\openbullet\OpenBulletCLI\Program.cs(68,14,68,20): error CS0012: The type 'Attribute' is defined in an assembly that is not referenced. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
3>C:\Users\kelsey\fucked\openbullet\OpenBulletCLI\Program.cs(71,14,71,19): error CS0012: The type 'Attribute' is defined in an assembly that is not referenced. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
2>  OpenBullet -> C:\Users\kelsey\fucked\openbullet\OpenBullet\bin\Debug\OpenBullet.exe
2>          1 file(s) copied.
2>          1 file(s) copied.
2>          1 file(s) copied.
========== Build: 2 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

```


I do not consider this a successful build. Because it fails. Which my pull request fixes.

Cheers dude. :|

**Comment by kernelzeroday** [comment]
You can close this now I will be handling the community edition in my tree thanks :)

**Comment by openbullet** [comment]
Alright, just wanted to point out your readme's pretty pathetic but I never expected maturity in the first place! Keep at it, maybe through your hate you'll make some actual improvements who knows ^_^

**Comment by kernelzeroday** [comment]
Maturity is releasing software that builds. 

https://github.com/openbullet/openbullet/issues/28

Working as intended eh

**Pull request closed without merging**
